### PR TITLE
Bump core-js to 3.6.4

### PR DESCRIPTION
**Pull request by GauthierPLM**
I chose a minimal version of 3.0.0 to avoid to be restrictive regarding users' projects which might no require the latest version of core-js.

Not sure about this decision, could someone confirm it's a good idea?

### CODE REVIEW

**Comment by patrick-tolosa** [comment]
Thanks for the PR @GauthierPLM,

Since this project uses @vue/cli-service ^3.10.0, which in turn uses core-js 2, we need to keep using core-js 2.

Ideally, we wouldn't want core-js as part of our dependencies, but rather as a peer dependency, however, that can easily conflict with the project that's installing it.

We'll need to upgrade vue-cli as well, and only then we could upgrade core-js.
We're happy to hear suggestions if you have a different idea in mind.

**Comment by GauthierPLM** [comment]
I started to look into upgrading vue-cli to version 4.3 but as I started to use VueJS with vue-cli 4, I wasn't sure if the update would be straight forward or if I would have more stuff to change for it.

I'll give it a look (but can't guarantee anything) when I have time and see if vue-cli can be upgraded to vue-cli 4 without issues, and open a pull request for it if I succeed.

As far a I know, vue-cli 4 is now used by most VueJS projects, so it would be safe to upgrade the dependencies along with the code that depends on vue-cli 3.

**Comment by patrick-tolosa** [comment]
If you need any assistance with the PR feel free to ask here, it's appreciated.

Please keep in mind that we have a  constraint where we **must** provide backward compatibility for all vue-cli versions, so it looks like core-js will still be needed in the dependencies, even if at version ^3

**Comment by GauthierPLM** [comment]
Tell me if I am wrong, but from what I understand, upgrading core-js (with or without vue-cli) should not cause any inconsistencies. Core-js is not directly used directly in this project code, only in the build process managed by vue-cli.
At runtime, calls to function not implemented by the browser will be automatically forwarded to core-js instead of showing an error for an unknown function.

User' code will thus not change at all, and the files produced by the build will be the same (no function renamed, no breakage, ...). I check the [CHANGELOG](https://github.com/zloirock/core-js/blob/master/CHANGELOG.md#300---20190319) and did not see any deprecation. Given the popularity of core-js and it's important role in modern development, I doubt the developers would take the risk of breaking other libraries.

Meanwhile, upgrading core-js will ensure more JS features are available in older browsers, more bugs fixed, and a better consistency between projects.

Thus, I think it's safe to upgrade it.
Also, it seems that vue-cli always add core-js to new projects in the last version in order to ensure comparability with older browsers. Instead of ensuring the compatibility by themselves, VueJS devs rely on it and from my experience maintaining a website running in IE11, it works well.

**Comment by patrick-tolosa** [comment]
In short, babel has three types of core-js integrations:
- Bundle with your build, 
- Reference in your build,
- Do nothing.

For libraries, you usually reference core-js in your build, you can see it in our bundle file like this:

``` module.exports = require("core-js/modules/es6.symbol"); ```
This path does not exist in core-js 3, but it does exist in core-js 2.

this line is injected(eventually) by vue-cli.
A project that installs this repo and uses core-js 3 will crash at build time, that's why we include core-js 2 and why we can't just update it separately.

I'm not sure if this problem would also exist in vue-cli, but that's the first thing we'll want to address probably (maybe even get rid of vue-cli completely)

**Comment by patrick-tolosa** [comment]
We're closing this PR as we'll address this issue in future releases,
While this change solves some problems, it creates issues in a different area.

Ideally, the solution would drop the dependency on core-js all together.

**Pull request closed without merging**
